import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {  GoogleAnalytics } from '@next/third-parties/google'
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NavBar />
      <body className={inter.className}>{children}</body>
      <GoogleAnalytics gaId="G-BN804S2RP3" />
    </html>
  );
}
